### ISSUE TITLE
Text boxes in iOS/iPadOS Settings or plugins not readable

### ISSUE THREAD

**Issue by crmfyi** [saket61195/Dracula_obsidian_theme#11]
I'm noticing that using this theme does not allow me to read the values in text boxes when a value exists. I'll include various screenshots which demonstrate the view using this theme and one using the Obsidian base theme to demonstrate the difference. 

In essence, when a text box exists, like searching community plugins or in the core search interface of Obsidian on iOS/iPadOS, any text typed in is not readable. 
On iPad
![IMG_0962](https://github.com/saket61195/Dracula_obsidian_theme/assets/985252/1b5382ac-6b88-4b2a-9289-849a004283e3)

On iPhone using Dracula Plus
![IMG_3647](https://github.com/saket61195/Dracula_obsidian_theme/assets/985252/ff2c67d8-11df-4527-b2f1-250c085df714)
![IMG_3648](https://github.com/saket61195/Dracula_obsidian_theme/assets/985252/4c11deaf-63ae-429e-957a-24cdb74484d8)

On iPhone using Obsidian Nord
![IMG_3651](https://github.com/saket61195/Dracula_obsidian_theme/assets/985252/84ff4802-524e-4d11-827e-f460445320e8)
![IMG_3649](https://github.com/saket61195/Dracula_obsidian_theme/assets/985252/a6fe099c-0d67-474c-951a-ca7747096d86)

**Comment by saket61195** [comment]
thanks @crmfyi for reporting issue
i don't have apple device to verify this issue even i compare with nord theme my theme setting is different from nord
i am really sorry i can't help this issue.
if you have enough time to fix this issue you can fix i will merge that code into theme

**Comment by crmfyi** [comment]
@saket61195 I'm not actually sure where to try and fix it, but what I'm guessing is that the font size used in any text box is too large to display in the box. Before typing, I see "Search..." in the search box, for example, but upon typing, it goes blank. 

There is one thing I've noticed which I wonder if it could be happening. Take a look at the screenshots and notice that in the Search box of Nord, you see a magnifying glass on the left and Aa on the right, which are white, but are visible on a gray background. Notice that in Dracula Plus, the text box is white and you don't see the magnifying glass or the Aa. When text is typed in, you also don't see the circle with the x in it to clear the search box. 

Could it be that Dracula Plus is typing white letters on a white background, and therefore you can't see them? When I click where the Aa should be in the search box, it goes orange and is then visible. Could it be that the font color simply needs to be something other than white when typing in a text box? Is there an area of the code you could point me to that controls the color of the typed font? Maybe if it was simply black or orange, I could see it. I suppose better yet, if the background color of the text input box could be changed, maybe we could see the magnifying glass, Aa, and clear buttons. I wish I knew where to dive in and try and fix this, but perhaps this little bit more digging could help you discover where it might be resolved. Thank you for making the theme. I'm liking it a lot, with this one usability exception.
![IMG_907CB5254342-1](https://github.com/saket61195/Dracula_obsidian_theme/assets/985252/3a5ef4af-7438-4eab-86d0-7a2c61589585)

**Comment by saket61195** [comment]
thanks @crmfyi  for replaying after testing on mobile version i found this issue i will fix soon 
i will inform you soon after update so be patience and thanks again for explaning everything

**Comment by saket61195** [comment]
hi @crmfyi  thanks  for your proper explanation about issue its fixed now
you can check and in case you face any issue and in future you face any kind of issue, you can raise issue again.
Thanks again i learnt something new from this issue.
after your reply i will close this issue thread

**Comment by crmfyi** [comment]
Fantastic @saket61195 ! Thank you so much for fixing this! It had been an issue in a previous version of a legacy Dracula theme as well, but that developer was no longer continuing development of it. 

I REALLY appreciate you digging in and applying this fix. It makes Obsidian so much easier to use on mobile.
