### ISSUE TITLE
Bottom bar too crazy

### ISSUE THREAD

**Issue by huachuman** [saket61195/Dracula_obsidian_theme#12]
It's huge (tall and wide) and covers the left sidebar. Most themes make it really small. Is there any way to adjust that?

It goes away when I zoom way out of the interface with ctrl+-, but takes over completely when you zoom in a bit.

**Comment by saket61195** [comment]
send screen shot then i will understand your problem and send other theme screen shot for comparison

**Comment by huachuman** [comment]
Normal (interface zoomed out): ![image](https://github.com/saket61195/Dracula_obsidian_theme/assets/125603964/79dd4436-318d-4114-a871-4d6965cb0e14)
Crazy (interface normal size): ![image](https://github.com/saket61195/Dracula_obsidian_theme/assets/125603964/94eee188-b27e-4877-8de5-bf92e8ffea42)

This happens to most themes when I zoom in A LOT, but it happens with dracula a lot earlier than for other themes. Is there any way to adjust this bar?

I think it's an absolutely stunning theme and I would hate for others not to use it for this one simple problem.

**Comment by saket61195** [comment]
i don't have botton panel i have windows and linux but i don't see bottom panel
will you tell me how to activate?
after that i can fix it

**Comment by saket61195** [comment]
i use less plugin that why my bottom bar is not messy
anyway give you plugin list name so that i will install and test on this theme to fix your issue

**Comment by saket61195** [comment]
```css
.status-bar {
  font-size: var(--status-bar-font-size);
}
```

save the above text into folder .obsdian/snippets as bottom.css or any name, it will make status bar default or small
this is temporary solution
for permanent solution you need to provide all plugin you install after that i can test and try to fix

**Comment by huachuman** [comment]
I mean clearly the bar is wide because I have a lot of plugins, and clearly removing a few plugins that use that bar will make it smaller. I don't think it's necessary to give you a full list of plugins I use to troubleshoot.

The status-bar fix should work just fine. 

I do feel a little bit silly knowing that I probably could have just used the dev tools to figure out how to modify it.

Anyways thank you very much now I get to enjoy this beautiful theme!!!

edit: confirmed, your snippet works perfectly. That's a good enough solution to me. Cheers!
